export const tarotDeck = [
  {name:"The Fool", keys:["New beginnings","Innocence","Spontaneity","Leap of faith","Free spirit","Unlimited potential"]},
  {name:"The Magician", keys:["Power","Skill","Resourcefulness","Concentration","Action","Manifestation"]},
  {name:"The High Priestess", keys:["Intuition","Mystery","Subconscious","Inner voice","Divine knowledge","Silence"]},
  {name:"The Empress", keys:["Fertility","Abundance","Nurturing","Nature","Sensuality","Motherhood"]},
  {name:"The Emperor", keys:["Authority","Structure","Father figure","Leadership","Control","Protection"]},
  {name:"The Hierophant", keys:["Tradition","Conformity","Spiritual guidance","Education","Beliefs","Rituals"]},
  {name:"The Lovers", keys:["Love","Harmony","Choices","Union","Values","Relationships"]},
  {name:"The Chariot", keys:["Determination","Victory","Willpower","Direction","Self-discipline","Ambition"]},
  {name:"Strength", keys:["Courage","Inner strength","Compassion","Patience","Endurance","Gentle force"]},
  {name:"The Hermit", keys:["Introspection","Inner wisdom","Solitude","Guidance","Search for truth","Withdrawal"]},
  {name:"Wheel of Fortune", keys:["Cycles","Fate","Turning point","Luck","Destiny","Change"]},
  {name:"Justice", keys:["Fairness","Truth","Law","Cause and effect","Accountability","Balance"]},
  {name:"The Hanged Man", keys:["Surrender","New perspective","Pause","Letting go","Sacrifice","Reversal"]},
  {name:"Death", keys:["Endings","Transformation","Transition","Release","Metamorphosis","New chapter"]},
  {name:"Temperance", keys:["Balance","Moderation","Patience","Harmony","Purpose","Healing"]},
  {name:"The Devil", keys:["Bondage","Materialism","Attachment","Shadow self","Temptation","Obsession"]},
  {name:"The Tower", keys:["Upheaval","Revelation","Sudden change","Awakening","Destruction of false beliefs","Chaos"]},
  {name:"The Star", keys:["Hope","Renewal","Serenity","Inspiration","Guidance","Faith"]},
  {name:"The Moon", keys:["Illusion","Fear","Unconscious","Intuition","Dreams","The unknown"]},
  {name:"The Sun", keys:["Success","Joy","Positivity","Vitality","Clarity","Warmth"]},
  {name:"Judgement", keys:["Rebirth","Inner calling","Absolution","Awakening","Decision","Renewal"]},
  {name:"The World", keys:["Completion","Accomplishment","Travel","Wholeness","Integration","Fulfillment"]},
  {name:"Ace of Wands", keys:["Inspiration","New venture","Creative spark","Potential","Growth","Excitement"]},
  {name:"Two of Wands", keys:["Planning","Future goals","Expansion","Discovery","Partnership","Decisions"]},
  {name:"Three of Wands", keys:["Progress","Confidence","Exploration","Foresight","Leadership","Expansion"]},
  {name:"Four of Wands", keys:["Celebration","Stability","Harmony","Homecoming","Community","Joy"]},
  {name:"Five of Wands", keys:["Conflict","Competition","Disagreement","Tension","Challenge","Growth"]},
  {name:"Six of Wands", keys:["Victory","Recognition","Success","Achievement","Public acclaim","Confidence"]},
  {name:"Seven of Wands", keys:["Perseverance","Defensiveness","Standing your ground","Challenge","Determination","Courage"]},
  {name:"Eight of Wands", keys:["Speed","Action","Movement","Air travel","Clear communication","Swiftness"]},
  {name:"Nine of Wands", keys:["Resilience","Perseverance","Last stand","Boundaries","Fatigue","Strength"]},
  {name:"Ten of Wands", keys:["Burden","Responsibility","Hard work","Completion","Overload","Release"]},
  {name:"Ace of Cups", keys:["New love","Emotional new beginning","Compassion","Creativity","Intuition","Overflow"]},
  {name:"Two of Cups", keys:["Partnership","Connection","Attraction","Unity","Balance","Harmony"]},
  {name:"Three of Cups", keys:["Celebration","Friendship","Community","Abundance","Creativity","Joy"]},
  {name:"Four of Cups", keys:["Contemplation","Apathy","Re-evaluation","Discontent","Introspection","Awareness"]},
  {name:"Five of Cups", keys:["Loss","Regret","Disappointment","Grief","Focus on the negative","Healing"]},
  {name:"Six of Cups", keys:["Nostalgia","Memories","Reunion","Generosity","Innocence","Childhood"]},
  {name:"Seven of Cups", keys:["Fantasy","Choice","Wishful thinking","Illusion","Daydreams","Possibilities"]},
  {name:"Eight of Cups", keys:["Walk away","Letting go","Searching for meaning","Abandonment","Travel","Growth"]},
  {name:"Nine of Cups", keys:["Contentment","Satisfaction","Fulfillment","Wishes coming true","Comfort","Gratitude"]},
  {name:"Ten of Cups", keys:["Divine love","Blissful relationships","Emotional abundance","Harmony","Peace","Completion"]},
  {name:"Ace of Swords", keys:["New idea","Mental clarity","Breakthrough","Truth","Justice","Focus"]},
  {name:"Two of Swords", keys:["Difficult decisions","Stalemate","Avoidance","Weighing options","Peace","Impasse"]},
  {name:"Three of Swords", keys:["Heartbreak","Sorrow","Painful truth","Separation","Release","Healing"]},
  {name:"Four of Swords", keys:["Rest","Recuperation","Contemplation","Retreat","Recharge","Stillness"]},
  {name:"Five of Swords", keys:["Conflict","Defeat","Win at all costs","Betrayal","Hollow victory","Learning"]},
  {name:"Six of Swords", keys:["Transition","Moving forward","Journey","Rite of passage","Change","Healing"]},
  {name:"Seven of Swords", keys:["Deception","Strategy","Theft","Dishonesty","Cleverness","Secret"]},
  {name:"Eight of Swords", keys:["Imprisonment","Self-victimization","Entrapment","Isolation","Limitations","Release"]},
  {name:"Nine of Swords", keys:["Anxiety","Worry","Nightmares","Fear","Guilt","Overthinking"]},
  {name:"Ten of Swords", keys:["Painful ending","Deep crisis","Rock bottom","Betrayal","Victimization","New dawn"]},
  {name:"Ace of Pentacles", keys:["New financial opportunity","Prosperity","Abundance","Manifestation","Resource","Stability"]},
  {name:"Two of Pentacles", keys:["Balance","Adaptability","Time management","Juggling","Prioritization","Flexibility"]}
];
